import = [ "~/.config/alacritty/themes/themes/inferno.toml" ]
[env]
TERM = "xterm-256color"


[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(http:|https:)"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[font]
size = 13.0


[selection]
save_to_clipboard = false

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/bash"

[window]
decorations = "none"